/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partidoonetomany;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvaro Llano
 */
public class VistaCargarEncuentros extends javax.swing.JInternalFrame {

    EntityManagerFactory emf = null;
    EntityManager em = null;
    /**
     * Creates new form VistaCargarEncuentros
     */
    public VistaCargarEncuentros() {
        initComponents();
        
        emf = null;
        em = null;
        emf = Persistence.createEntityManagerFactory("C:/base/PartidoOneToMany.odb");
        em = emf.createEntityManager();

        CargarEquipo();
        CargarArbitro();
        listarPartido();
        
        actualizar.setEnabled(false);
        borrar.setEnabled(false);
    }
    
    public void CargarEquipo() {
        
        try {
            Query consultaEquipos = em.createQuery("SELECT equipo1 FROM Equipo equipo1");
            List<Equipo> ResultadosEquipo = consultaEquipos.getResultList();
            for (Equipo e : ResultadosEquipo) {
                
                localBox.addItem(e);
                visitanteBox.addItem(e);
            }
            

        } catch (Exception e) {
            System.err.println("ERROR AL INTENTAR LISTAR LOS EQUIPOS:" + e);
        }
        
    }
    
    public void CargarArbitro() {
        
        try {
            Query consultaArbitro = em.createQuery("SELECT arbitro FROM Arbitro arbitro");
            List<Arbitro> ResultadosArbitro = consultaArbitro.getResultList();
            for (Arbitro a : ResultadosArbitro) {
                
                arbitroBox.addItem(a);
            }
            

        } catch (Exception e) {
            System.err.println("ERROR AL INTENTAR LISTAR LOS ARBITROS:" + e);
        }
        
    }
    
    public void listarPartido() {
        Query consultaPartido = em.createQuery("SELECT partido FROM Partido partido");
        List<Partido> ResultadosPartido = consultaPartido.getResultList();
        DefaultTableModel modelo = (DefaultTableModel) tablePartido.getModel();
        modelo.setRowCount(0);
        for (Partido p : ResultadosPartido) {
            try {
                modelo.addRow(new Object[]{p.getIdPartido(),p.getRonda(), p.getArbitro().getNombreArbitro() ,p.getLocal().getNombreEquipo(), p.getVisitante().getNombreEquipo()});
            
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPartidoTxt = new javax.swing.JTextField();
        rondaPartidoTxt = new javax.swing.JTextField();
        arbitroBox = new javax.swing.JComboBox();
        localBox = new javax.swing.JComboBox();
        visitanteBox = new javax.swing.JComboBox();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePartido = new javax.swing.JTable();
        actualizar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        localBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localBoxActionPerformed(evt);
            }
        });

        visitanteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitanteBoxActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        tablePartido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RONDA", "ARBITRO", "EQUIPO LOCAL", "EQUIPO VISITANTE"
            }
        ));
        tablePartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePartidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePartido);

        actualizar.setText("Actualizar");
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarMouseClicked(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idPartidoTxt)
                        .addComponent(rondaPartidoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addComponent(arbitroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(localBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visitanteBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE))
                    .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idPartidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rondaPartidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arbitroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(localBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(visitanteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localBoxActionPerformed

    private void visitanteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitanteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitanteBoxActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        // TODO add your handling code here:
        
        try {
            String idPartido = idPartidoTxt.getText();
            String Ronda = rondaPartidoTxt.getText();
            Arbitro arbitro = (Arbitro) arbitroBox.getSelectedItem();
            Equipo equipoLocal = (Equipo) localBox.getSelectedItem();
            Equipo equipoVisitante = (Equipo) visitanteBox.getSelectedItem();
            
            Partido partido = new Partido(idPartido, Ronda, equipoLocal, equipoVisitante, arbitro);
            
            em.getTransaction().begin();
            em.persist(partido);
            em.getTransaction().commit();
            
            JOptionPane.showMessageDialog(rootPane, "Guardado Exitoso");    
            
            idPartidoTxt.setText("");
            rondaPartidoTxt.setText("");
            
            listarPartido();


            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_guardarMouseClicked

    private void tablePartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePartidoMouseClicked
        // TODO add your handling code here:
        int fila = tablePartido.getSelectedRow();
        Object id = tablePartido.getValueAt(fila, 0);       
        
        Partido partido = em.find(Partido.class, id);
        
        idPartidoTxt.setEnabled(false);
        
        String idPartido = partido.getIdPartido();
        String rondaPartido = partido.getRonda();
        Arbitro arbitro = (Arbitro) partido.arbitro;
        Equipo equipoLocal = (Equipo) partido.Local;
        Equipo equipoVisitante = (Equipo) partido.Visitante;

        
        idPartidoTxt.setText(idPartido);
        rondaPartidoTxt.setText(rondaPartido);
        arbitroBox.setSelectedItem(arbitro);
        localBox.setSelectedItem(equipoLocal);
        visitanteBox.setSelectedItem(equipoVisitante);
        
        guardar.setEnabled(false);
        borrar.setEnabled(true);
        actualizar.setEnabled(true);
        
        
    }//GEN-LAST:event_tablePartidoMouseClicked

    private void actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseClicked
        // TODO add your handling code here:
        
        int fila = tablePartido.getSelectedRow();
        Object id = tablePartido.getValueAt(fila, 0);   
        
        Partido partido = em.find(Partido.class, id);
        
        
        String idPartido = idPartidoTxt.getText();
        String Ronda = rondaPartidoTxt.getText();
        Arbitro arbitro = (Arbitro) arbitroBox.getSelectedItem();
        Equipo equipoLocal = (Equipo) localBox.getSelectedItem();
        Equipo equipoVisitante = (Equipo) visitanteBox.getSelectedItem();
        
        partido.setIdPartido(idPartido);
        partido.setRonda(Ronda);
        partido.setArbitro(arbitro);
        partido.setLocal(equipoLocal);
        partido.setVisitante(equipoVisitante);
        
        em.getTransaction().begin();
        em.persist(partido);
        em.getTransaction().commit();        

        JOptionPane.showMessageDialog(rootPane, "Actualizado Exitoso");          
        listarPartido();

        
        
        idPartidoTxt.setText("");
        rondaPartidoTxt.setText("");
        arbitroBox.setSelectedIndex(0);
        localBox.setSelectedIndex(0);
        visitanteBox.setSelectedIndex(0);        

        idPartidoTxt.setEnabled(true);
        
        guardar.setEnabled(true);
        borrar.setEnabled(false);
        actualizar.setEnabled(false);
        
    }//GEN-LAST:event_actualizarMouseClicked

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        // TODO add your handling code here:
        
        int fila = tablePartido.getSelectedRow();
        Object id = tablePartido.getValueAt(fila, 0);   
        
        Partido partido = em.find(Partido.class, id);       
        em.getTransaction().begin();
        em.remove(partido);
        em.getTransaction().commit();

        JOptionPane.showMessageDialog(rootPane, "Borrado Exitoso");
        
        idPartidoTxt.setText("");
        rondaPartidoTxt.setText("");
        arbitroBox.setSelectedIndex(0);
        localBox.setSelectedIndex(0);
        visitanteBox.setSelectedIndex(0);        

        idPartidoTxt.setEnabled(true);
        guardar.setEnabled(true);
        borrar.setEnabled(false);
        actualizar.setEnabled(false);
        listarPartido();
    }//GEN-LAST:event_borrarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        idPartidoTxt.setText("");
        rondaPartidoTxt.setText("");
        arbitroBox.setSelectedIndex(0);
        localBox.setSelectedIndex(0);
        visitanteBox.setSelectedIndex(0);        

        idPartidoTxt.setEnabled(true);

        guardar.setEnabled(true);
        borrar.setEnabled(false);
        actualizar.setEnabled(false);
        
        listarPartido();
    }//GEN-LAST:event_cancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JComboBox arbitroBox;
    private javax.swing.JButton borrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField idPartidoTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox localBox;
    private javax.swing.JTextField rondaPartidoTxt;
    private javax.swing.JTable tablePartido;
    private javax.swing.JComboBox visitanteBox;
    // End of variables declaration//GEN-END:variables
}
