/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partidoonetomany;

/**
 *
 * @author Alvaro Llano
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registrarEncuentro = new javax.swing.JMenuItem();
        registrarEquipo = new javax.swing.JMenu();
        RegistrarEquipo = new javax.swing.JMenuItem();
        registrarArbitro = new javax.swing.JMenu();
        RegistrarArbitro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jMenu1.setText("Encuentros");

        registrarEncuentro.setText("Registrar un Encuentro");
        registrarEncuentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEncuentroActionPerformed(evt);
            }
        });
        jMenu1.add(registrarEncuentro);

        jMenuBar1.add(jMenu1);

        registrarEquipo.setText("Equipos");

        RegistrarEquipo.setText("Registrar Equipos");
        RegistrarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarEquipoMouseClicked(evt);
            }
        });
        RegistrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEquipoActionPerformed(evt);
            }
        });
        registrarEquipo.add(RegistrarEquipo);

        jMenuBar1.add(registrarEquipo);

        registrarArbitro.setText("Arbitros");

        RegistrarArbitro.setText("Registrar Arbitros");
        RegistrarArbitro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarArbitroMouseClicked(evt);
            }
        });
        RegistrarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarArbitroActionPerformed(evt);
            }
        });
        registrarArbitro.add(RegistrarArbitro);

        jMenuBar1.add(registrarArbitro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEncuentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEncuentroActionPerformed
        // TODO add your handling code here:
        VistaCargarEncuentros vistacargarencuentros = new VistaCargarEncuentros();
        Escritorio.add(vistacargarencuentros);
        vistacargarencuentros.show();
    }//GEN-LAST:event_registrarEncuentroActionPerformed

    private void RegistrarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarEquipoMouseClicked
        
    }//GEN-LAST:event_RegistrarEquipoMouseClicked

    private void RegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEquipoActionPerformed
        // TODO add your handling code here:
        //Se instancia el objeto para desplegar en la pantalla
        VistaCargarEquipos vistaCE = new VistaCargarEquipos();
        Escritorio.add(vistaCE);
        vistaCE.show();
    }//GEN-LAST:event_RegistrarEquipoActionPerformed

    private void RegistrarArbitroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarArbitroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarArbitroMouseClicked

    private void RegistrarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarArbitroActionPerformed
        // TODO add your handling code here:
        VistaCargarArbitros vistacargararbitros = new VistaCargarArbitros();
        Escritorio.add(vistacargararbitros);
        vistacargararbitros.show();
                
    }//GEN-LAST:event_RegistrarArbitroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem RegistrarArbitro;
    private javax.swing.JMenuItem RegistrarEquipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu registrarArbitro;
    private javax.swing.JMenuItem registrarEncuentro;
    private javax.swing.JMenu registrarEquipo;
    // End of variables declaration//GEN-END:variables
}
